sudo : required
services:
  - docker

before_install:
  - docker build -t rahul04021993/docker-learn -f Dockerfile.dev .

scripts:
  - docker run rahul04021993/docker-learn npm run test -- --coverage
